// FILE: ipcChannels.ts
// Purpose: Defines the data-only IPC channel contract shared by Electron main and preload.
// Layer: Desktop IPC contract

export const DESKTOP_IPC_CHANNELS = {
  pickFolder: "desktop:pick-folder",
  saveFile: "desktop:save-file",
  confirm: "desktop:confirm",
  setTheme: "desktop:set-theme",
  setAppTheme: "desktop:set-app-theme",
  setSpacesMenu: "desktop:set-spaces-menu",
  contextMenu: "desktop:context-menu",
  openExternal: "desktop:open-external",
  showInFolder: "desktop:show-in-folder",
  clipboardWriteImage: "desktop:clipboard-write-image",
  windowMinimize: "desktop:window-minimize",
  windowToggleMaximize: "desktop:window-toggle-maximize",
  windowClose: "desktop:window-close",
  windowGetState: "desktop:window-get-state",
  windowState: "desktop:window-state",
  menuAction: "desktop:menu-action",
  updateState: "desktop:update-state",
  updateGetState: "desktop:update-get-state",
  updateCheck: "desktop:update-check",
  updateDownload: "desktop:update-download",
  updateInstall: "desktop:update-install",
  notificationsIsSupported: "desktop:notifications-is-supported",
  notificationsShow: "desktop:notifications-show",
  mediaRequestMicrophoneAccess: "desktop:media-request-microphone-access",
  mediaSetVoiceRecordingActive: "desktop:media-set-voice-recording-active",
  accountAuth: {
    getState: "desktop:account-auth-get-state",
    requestSignIn: "desktop:account-auth-request-sign-in",
    requestSignUp: "desktop:account-auth-request-sign-up",
    signOut: "desktop:account-auth-sign-out",
    callbackStarted: "desktop:account-auth-callback-started",
    authenticated: "penkra-account:authenticated",
    userUpdated: "penkra-account:user-updated",
    error: "penkra-account:error",
  },
  zoomFactor: "desktop:zoom-factor",
  zoomFactorChanged: "desktop:zoom-factor-changed",
  wsUrl: "desktop:get-ws-url",
  transcribeVoice: "desktop:server-transcribe-voice",
  storageMigration: {
    read: "desktop:storage-migration-read",
    acknowledge: "desktop:storage-migration-acknowledge",
  },
  appRuntime: {
    hostMessage: "penkra-app:host-message",
    rendererMessage: "penkra-app:renderer-message",
    ready: "penkra-app:ready",
    permissionQuery: "penkra-app:permission-query",
    permissionRequest: "penkra-app:permission-request",
    identityGet: "penkra-app:identity-get",
    settingGet: "penkra-app:setting-get",
    settingSet: "penkra-app:setting-set",
    settingReset: "penkra-app:setting-reset",
    secretGet: "penkra-app:secret-get",
    secretSet: "penkra-app:secret-set",
    secretDelete: "penkra-app:secret-delete",
    filePick: "penkra-app:file-pick",
    fileList: "penkra-app:file-list",
    fileReadText: "penkra-app:file-read-text",
    fileWriteText: "penkra-app:file-write-text",
    fileListDirectory: "penkra-app:file-list-directory",
    fileOpenChild: "penkra-app:file-open-child",
    fileRevoke: "penkra-app:file-revoke",
    networkFetch: "penkra-app:network-fetch",
    rawSocketExchange: "penkra-app:raw-socket-exchange",
    processRun: "penkra-app:process-run",
  },
  appInstallations: {
    state: "desktop:app-installations-state",
    getState: "desktop:app-installations-get-state",
    installRegistry: "desktop:app-installations-install-registry",
    updateRegistry: "desktop:app-installations-update-registry",
    rollbackRegistry: "desktop:app-installations-rollback-registry",
    setEnabled: "desktop:app-installations-set-enabled",
    setPermission: "desktop:app-installations-set-permission",
    getSettings: "desktop:app-installations-get-settings",
    setSetting: "desktop:app-installations-set-setting",
    resetSetting: "desktop:app-installations-reset-setting",
    setSkillEnabled: "desktop:app-installations-set-skill-enabled",
    uninstall: "desktop:app-installations-uninstall",
    removeData: "desktop:app-installations-remove-data",
  },
  appRegistry: {
    list: "desktop:app-registry-list",
    get: "desktop:app-registry-get",
    getArtifact: "desktop:app-registry-get-artifact",
    getFeedback: "desktop:app-registry-get-feedback",
    setRating: "desktop:app-registry-set-rating",
    setReview: "desktop:app-registry-set-review",
  },
  appTabs: {
    listingRequested: "desktop:app-tabs-listing-requested",
    consumeListingRequest: "desktop:app-tabs-consume-listing-request",
    opened: "desktop:app-tabs-opened",
    state: "desktop:app-tabs-state",
    list: "desktop:app-tabs-list",
    open: "desktop:app-tabs-open",
    openFromApps: "desktop:app-tabs-open-from-apps",
    attach: "desktop:app-tabs-attach",
    setBounds: "desktop:app-tabs-set-bounds",
    setVisible: "desktop:app-tabs-set-visible",
    navigate: "desktop:app-tabs-navigate",
    close: "desktop:app-tabs-close",
  },
  appDiagnostics: {
    list: "desktop:app-diagnostics-list",
  },
  browser: {
    state: "desktop:browser-state",
    open: "desktop:browser-open",
    close: "desktop:browser-close",
    hide: "desktop:browser-hide",
    getState: "desktop:browser-get-state",
    setBounds: "desktop:browser-set-bounds",
    attachWebview: "desktop:browser-attach-webview",
    detachWebview: "desktop:browser-detach-webview",
    requestOpenPanel: "desktop:browser-use-request-open-panel",
    copyLink: "desktop:browser-copy-link",
    requestCopyLink: "desktop:browser-request-copy-link",
    copyScreenshotToClipboard: "desktop:browser-copy-screenshot-to-clipboard",
    captureScreenshot: "desktop:browser-capture-screenshot",
    executeCdp: "desktop:browser-execute-cdp",
    findInPage: "desktop:browser-find-in-page",
    stopFindInPage: "desktop:browser-stop-find-in-page",
    navigate: "desktop:browser-navigate",
    reload: "desktop:browser-reload",
    goBack: "desktop:browser-go-back",
    goForward: "desktop:browser-go-forward",
    newTab: "desktop:browser-new-tab",
    closeTab: "desktop:browser-close-tab",
    selectTab: "desktop:browser-select-tab",
    openDevTools: "desktop:browser-open-devtools",
  },
} as const;

export const BROWSER_IPC_CHANNELS = DESKTOP_IPC_CHANNELS.browser;
export const DESKTOP_WS_URL_CHANNEL = DESKTOP_IPC_CHANNELS.wsUrl;
export const SERVER_TRANSCRIBE_VOICE_CHANNEL = DESKTOP_IPC_CHANNELS.transcribeVoice;
export const APP_RUNTIME_IPC_CHANNELS = DESKTOP_IPC_CHANNELS.appRuntime;
