import {
  SpaceCreatedPayload as ContractsSpaceCreatedPayloadSchema,
  SpaceUpdatedPayload as ContractsSpaceUpdatedPayloadSchema,
  SpaceArchivedPayload as ContractsSpaceArchivedPayloadSchema,
  SpaceRestoredPayload as ContractsSpaceRestoredPayloadSchema,
  SpaceDeletedPayload as ContractsSpaceDeletedPayloadSchema,
  FolderCreatedPayload as ContractsFolderCreatedPayloadSchema,
  FolderUpdatedPayload as ContractsFolderUpdatedPayloadSchema,
  FolderMovedPayload as ContractsFolderMovedPayloadSchema,
  FolderDeletedPayload as ContractsFolderDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadUpdatedPayload as ContractsThreadUpdatedPayloadSchema,
  ThreadPinnedMessageAddedPayload as ContractsThreadPinnedMessageAddedPayloadSchema,
  ThreadPinnedMessageRemovedPayload as ContractsThreadPinnedMessageRemovedPayloadSchema,
  ThreadPinnedMessageDoneSetPayload as ContractsThreadPinnedMessageDoneSetPayloadSchema,
  ThreadPinnedMessageLabelSetPayload as ContractsThreadPinnedMessageLabelSetPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadTurnStartCancelledPayload as ContractsThreadTurnStartCancelledPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadConversationRolledBackPayload as ContractsThreadConversationRolledBackPayloadSchema,
  ThreadConversationRollbackRequestedPayload as ContractsThreadConversationRollbackRequestedPayloadSchema,
  ThreadMessageEditResendRequestedPayload as ContractsThreadMessageEditResendRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@penkra/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const SpaceCreatedPayload = ContractsSpaceCreatedPayloadSchema;
export const SpaceUpdatedPayload = ContractsSpaceUpdatedPayloadSchema;
export const SpaceArchivedPayload = ContractsSpaceArchivedPayloadSchema;
export const SpaceRestoredPayload = ContractsSpaceRestoredPayloadSchema;
export const SpaceDeletedPayload = ContractsSpaceDeletedPayloadSchema;
export const FolderCreatedPayload = ContractsFolderCreatedPayloadSchema;
export const FolderUpdatedPayload = ContractsFolderUpdatedPayloadSchema;
export const FolderMovedPayload = ContractsFolderMovedPayloadSchema;
export const FolderDeletedPayload = ContractsFolderDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadUpdatedPayload = ContractsThreadUpdatedPayloadSchema;
export const ThreadPinnedMessageAddedPayload = ContractsThreadPinnedMessageAddedPayloadSchema;
export const ThreadPinnedMessageRemovedPayload = ContractsThreadPinnedMessageRemovedPayloadSchema;
export const ThreadPinnedMessageDoneSetPayload = ContractsThreadPinnedMessageDoneSetPayloadSchema;
export const ThreadPinnedMessageLabelSetPayload = ContractsThreadPinnedMessageLabelSetPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadTurnStartCancelledPayload = ContractsThreadTurnStartCancelledPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadConversationRollbackRequestedPayload =
  ContractsThreadConversationRollbackRequestedPayloadSchema;
export const ThreadConversationRolledBackPayload =
  ContractsThreadConversationRolledBackPayloadSchema;
export const ThreadMessageEditResendRequestedPayload =
  ContractsThreadMessageEditResendRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
